export const RuAbc = [
  [
    { value: "ё", className: '' },
    { value: "1", className: '' },
    { value: "2", className: '' },
    { value: "3", className: '' },
    { value: "4", className: '' },
    { value: "5", className: '' },
    { value: "6", className: '' },
    { value: "7", className: '' },
    { value: "8", className: '' },
    { value: "9", className: '' },
    { value: "0", className: '' },
    { value: "-", className: '' },
    { value: "=", className: '' },
    { value: "Backspace", className: 'backspace' },
  ],
  [
    { value: "Tab", className: 'tab' },
    { value: "й", className: '' },
    { value: "ц", className: '' },
    { value: "у", className: '' },
    { value: "к", className: '' },
    { value: "е", className: '' },
    { value: "н", className: '' },
    { value: "г", className: '' },
    { value: "ш", className: '' },
    { value: "щ", className: '' },
    { value: "з", className: '' },
    { value: "х", className: '' },
    { value: "ъ", className: '' },
    { value: "\\", className: '' },
    { value: "Del", className: '' },
  ],
  [
    { value: "CapsLock", className: 'capsLock' },
    { value: "ф", className: '' },
    { value: "ы", className: '' },
    { value: "в", className: '' },
    { value: "а", className: '' },
    { value: "п", className: '' },
    { value: "р", className: '' },
    { value: "о", className: '' },
    { value: "л", className: '' },
    { value: "д", className: '' },
    { value: "ж", className: '' },
    { value: "э", className: '' },
    { value: "Enter", className: 'enter' },
  ],
  [
    { value: "Shift", className: 'shift' },
    { value: "я", className: '' },
    { value: "ч", className: '' },
    { value: "с", className: '' },
    { value: "м", className: '' },
    { value: "и", className: '' },
    { value: "т", className: '' },
    { value: "ь", className: '' },
    { value: "б", className: '' },
    { value: "ю", className: '' },
    { value: ".", className: '' },
    { value: "&#8657;", className: '' },
    { value: "Shift", className: 'shift' },
  ],
  [
    { value: "Ctrl", className: '' },
    { value: "Win", className: '' },
    { value: "Alt", className: '' },
    { value: " ", className: 'space' },
    { value: "Alt", className: '' },
    { value: "&#8656", className: '' },
    { value: "&#8659", className: '' },
    { value: "&#8658", className: '' },
    { value: "Ctrl", className: '' },
  ],
];
const RuAbcShift = [
  [
    { value: "Ё" },
    { value: "!" },
    { value: '"' },
    { value: "№" },
    { value: ";" },
    { value: "%" },
    { value: ":" },
    { value: "?" },
    { value: "*" },
    { value: "(" },
    { value: ")" },
    { value: "_" },
    { value: "+" },
    { value: "Backspace" },
  ],
  [
    { value: "Й" },
    { value: "Ц" },
    { value: "У" },
    { value: "К" },
    { value: "Е" },
    { value: "Н" },
    { value: "Г" },
    { value: "Ш" },
    { value: "Щ" },
    { value: "З" },
    { value: "Х" },
    { value: "Ъ" },
  ],
  [
    { value: "Ф" },
    { value: "Ы" },
    { value: "В" },
    { value: "А" },
    { value: "П" },
    { value: "Р" },
    { value: "О" },
    { value: "Л" },
    { value: "Д" },
    { value: "Ж" },
    { value: "Э" },
    { value: "/" },
  ],
  [
    { value: "Я" },
    { value: "Ч" },
    { value: "С" },
    { value: "М" },
    { value: "И" },
    { value: "Т" },
    { value: "Ь" },
    { value: "Б" },
    { value: "Ю" },
    { value: "," },
  ],
];
const EnAbc = [
  [
    { value: "`" },
    { value: "1" },
    { value: "2" },
    { value: "3" },
    { value: "4" },
    { value: "5" },
    { value: "6" },
    { value: "7" },
    { value: "8" },
    { value: "9" },
    { value: "0" },
    { value: "-" },
    { value: "=" },
    { value: "Backspace" },
  ],
  [
    { value: "q" },
    { value: "w" },
    { value: "e" },
    { value: "r" },
    { value: "t" },
    { value: "y" },
    { value: "u" },
    { value: "i" },
    { value: "o" },
    { value: "p" },
    { value: "[" },
    { value: "]" },
  ],
  [
    { value: "a" },
    { value: "s" },
    { value: "d" },
    { value: "f" },
    { value: "g" },
    { value: "h" },
    { value: "j" },
    { value: "k" },
    { value: "l" },
    { value: ";" },
    { value: "'" },
    { value: "\\" },
  ],
  [
    { value: "z" },
    { value: "x" },
    { value: "c" },
    { value: "v" },
    { value: "b" },
    { value: "n" },
    { value: "m" },
    { value: "," },
    { value: "." },
    { value: "/" },
  ],
];
const EnAbcShift = [
  [
    { value: "~" },
    { value: "!" },
    { value: "@" },
    { value: "#" },
    { value: "$" },
    { value: "%" },
    { value: "^" },
    { value: "&" },
    { value: "*" },
    { value: "(" },
    { value: ")" },
    { value: "_" },
    { value: "+" },
    { value: "Backspace" },
  ],
  [
    { value: "Q" },
    { value: "W" },
    { value: "E" },
    { value: "R" },
    { value: "T" },
    { value: "Y" },
    { value: "U" },
    { value: "I" },
    { value: "O" },
    { value: "P" },
    { value: "{" },
    { value: "}" },
  ],
  [
    { value: "A" },
    { value: "S" },
    { value: "D" },
    { value: "F" },
    { value: "G" },
    { value: "H" },
    { value: "J" },
    { value: "K" },
    { value: "L" },
    { value: ":" },
    { value: '"' },
    { value: "|" },
  ],
  [
    { value: "Z" },
    { value: "X" },
    { value: "C" },
    { value: "V" },
    { value: "B" },
    { value: "N" },
    { value: "M" },
    { value: "<" },
    { value: ">" },
    { value: "?" },
  ],
];
